<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBySkills($skills) {
        return $this->getEntityManager()
            ->createQuery('
              SELECT u, s FROM AppBundle:User u
              JOIN u.skills s
              WHERE s.name in (:skills)
            ')
            ->setParameter('skills', $skills)
            ->getResult();
    }
}
